const {directions,slides}=window.DESIGN_DATA;
const asset=(d,s='moodboard')=>`assets/${d.id}-${s}.png`;
const shot=(d,s,i)=>`<figure class="shot"><button data-image="${asset(d,s.slug)}" data-title="${d.name} · ${s.feature}" aria-label="Phóng to ${d.name}: ${s.feature}"><img loading="lazy" decoding="async" src="${asset(d,s.slug)}" alt="${d.name} — ${s.feature}" width="864" height="1872"></button><figcaption>0${i+1} / ${s.feature}<small>${s.headline.replaceAll('\n',' ')}</small></figcaption></figure>`;
document.querySelector('#jump').innerHTML=directions.map((d,i)=>`<a href="#${d.id}"><img src="${asset(d)}" alt="Moodboard ${d.name}" width="1536" height="1024"><span class="jump-label">0${i+1} · ${d.name}<small>Khám phá ↗</small></span></a>`).join('');
document.querySelector('#directions').innerHTML=directions.map((d,i)=>`<section class="direction" id="${d.id}"><div class="dir-head"><div><span class="eyebrow"><span class="number">0${i+1}</span>${d.tag}</span><h2>${d.name}</h2><div class="swatches">${d.colors.map(c=>`<span class="swatch" style="background:${c}" title="${c}" role="img" aria-label="Màu ${c}"></span>`).join('')}</div></div><p>${d.lead}</p></div><button class="board" data-image="${asset(d)}" data-title="${d.name} · Moodboard" aria-label="Phóng to moodboard ${d.name}"><img loading="lazy" decoding="async" src="${asset(d)}" alt="Moodboard ${d.name}: thế giới, sinh vật, chất liệu và bảng màu" width="1536" height="1024"></button><div class="caption"><span>MOODBOARD / ${d.name.toUpperCase()}</span><span>Nhấn ảnh để xem lớn & tải bản gốc ↗</span></div><div class="rationale">${d.why.map(([h,p])=>`<div><h3>${h}</h3><p>${p}</p></div>`).join('')}</div><div class="tradeoff"><div><b>ĐIỂM ĐÁNH ĐỔI</b><p>${d.trade}</p></div><div><b>CÂU HỎI CẦN KIỂM CHỨNG</b><p>${d.test}</p></div></div><div class="screen-heading"><h3>Bốn khoảnh khắc, một thế giới.</h3><span>Concept ảnh App Store · English · ${d.choose}</span></div><div class="screens">${slides.map((s,j)=>shot(d,s,j)).join('')}</div></section>`).join('');
const tabs=document.querySelector('#tabs');
tabs.innerHTML=slides.map((s,i)=>`<button data-slide="${i}" aria-pressed="${i===0}">${s.feature}</button>`).join('');
function compare(i){document.querySelector('#compare-grid').innerHTML=directions.map(d=>`<div><h3>${d.name}</h3>${shot(d,slides[i],i)}</div>`).join('');tabs.querySelectorAll('button').forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));}
tabs.addEventListener('click',e=>{const b=e.target.closest('[data-slide]');if(b)compare(Number(b.dataset.slide));});compare(0);
const viewer=document.querySelector('#viewer');
document.addEventListener('click',e=>{const b=e.target.closest('[data-image]');if(!b)return;const img=document.querySelector('#viewer-img');img.src=b.dataset.image;img.alt=b.dataset.title;document.querySelector('#viewer-title').textContent=b.dataset.title;document.querySelector('#download').href=b.dataset.image;viewer.showModal();document.body.classList.add('modal-open');});
document.querySelector('#close').addEventListener('click',()=>viewer.close());viewer.addEventListener('close',()=>document.body.classList.remove('modal-open'));viewer.addEventListener('click',e=>{if(e.target===viewer){const r=viewer.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)viewer.close();}});
document.querySelector('#copy-link').addEventListener('click',async()=>{const status=document.querySelector('#copy-status');try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(location.href);}else{const input=document.createElement('textarea');input.value=location.href;input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();const ok=document.execCommand('copy');input.remove();if(!ok)throw new Error('copy');}status.textContent='Đã sao chép link.';}catch{status.textContent='Sao chép địa chỉ trên thanh URL để chia sẻ.';}});
